### ISSUE TITLE
list-alt icon missing spacing on the bottom

### ISSUE THREAD

**Issue by ghost** [shyaniv7/react-native-fontawesome-pro#7]
### Description

I've described my issue on the [font awesome board](https://github.com/FortAwesome/Font-Awesome/issues/13191) here but it doesn't seem like they are experiencing this issue.

Wondering if you guys knew the reason behind why the icon would look like this?

<img width="51" alt="screen shot 2018-05-22 at 4 16 07 pm" src="https://user-images.githubusercontent.com/4645400/40390705-ae119654-5ddb-11e8-8133-046d94ecf206.png">

### Environment

* What `react-native-fontawesome-pro` version are you using? **"react-native-fontawesome-pro": "^1.0.12",**
* What `react-native` version are you using? **react-native-cli: 2.0.1**
* Does the issue occur on IOS, Android or Both? **Only checked on IOS**

**Comment by shyaniv7** [comment]
Thank you for reaching out.

I had a similar issue with the plus-square icon in the light package, it just didnt look right for some reason.

I will investigate a bit more but my gut tells me that it has something to do with the way the `react-native-svg` package prints the svg that is provided by font awesome pro.

does the same thing happens when you use the same icon from the regular or solid packages?

Thanks,
Yaniv

**Comment by ghost** [comment]
Hey @shyaniv7 

That makes sense. The `list-alt` icon seems to look fine in all over the other packages besides the light.

**Comment by shyaniv7** [comment]
Unfortunately without manually modifying the svg on the light package im not sure how else to fix this issue.

Closing this issue
